services:
  db:
    ports:
      - '27017:27017'
    restart: 'no'

  redis:
    ports:
      - '6379:6379'
    restart: 'no'

  backend:
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development

  minecraft:
    restart: 'no'
    ports:
      - '25565:25565'
    environment:
      - MC_ENV=development
      - API_URL=http://localhost:3000
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    stdin_open: true
    tty: true

  frontend:
    ports:
      - '80:80'
